steps:
- name: node:16
  entrypoint: git
  args: ['submodule', 'update', '--init', '--recursive']
- name: node:16
  entrypoint: npm
  args: ['install', '--unsafe-perm']
- name: node:16
  entrypoint: npm
  args: ['run', 'system-test']
